# Generated by Django 5.1.3 on 2024-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mission', models.TextField()),
                ('Vision', models.TextField()),
                ('aboutus_title', models.CharField(max_length=100)),
                ('Core_values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfolio_category', models.CharField(max_length=100)),
                ('Project_title', models.CharField(max_length=100)),
                ('Project_Techstack', models.CharField(max_length=100)),
                ('Project_KeyFeatures', models.TextField()),
                ('Project_Impact', models.TextField()),
                ('Project_live_link', models.CharField(max_length=100)),
                ('Project_Repos_link', models.CharField(max_length=100)),
                ('Project_case_study_link', models.CharField(max_length=100)),
                ('Project_description', models.TextField()),
                ('Project_image', models.ImageField(upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
        ),
    ]
