# Generated by Django 5.1.3 on 2025-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('UNDER_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_ABOVE', '65 and above')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, choices=[('URBAN', 'Urban'), ('SEMI_URBAN', 'Semi-Urban'), ('RURAL', 'Rural')], max_length=20, null=True)),
                ('gender_identity', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('state_union_territory', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('NO_FORMAL_EDUCATION', 'No formal education'), ('PRIMARY_EDUCATION', 'Primary education'), ('SECONDARY_EDUCATION', 'Secondary education'), ('HIGHER_SECONDARY_EDUCATION', 'Higher secondary education'), ('BACHELORS_DEGREE', "Bachelor's degree"), ('MASTERS_OR_HIGHER', "Master's degree or higher")], max_length=50, null=True)),
                ('familiarity_with_violence', models.CharField(blank=True, choices=[('VERY_FAMILIAR', 'Very familiar'), ('SOMEWHAT_FAMILIAR', 'Somewhat familiar'), ('NOT_VERY_FAMILIAR', 'Not very familiar'), ('NOT_AT_ALL_FAMILIAR', 'Not at all familiar')], max_length=50, null=True)),
                ('witnessed_violence', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=50, null=True)),
                ('forms_of_violence', models.CharField(blank=True, choices=[('PHYSICAL_ASSAULT', 'Physical assault (e.g., hitting, kicking, pushing)'), ('SEXUAL_ASSAULT', 'Sexual assault or rape'), ('VERBAL_ABUSE', 'Verbal abuse or name-calling'), ('CONTROLLING_BEHAVIOR', 'Controlling Behavior (e.g., isolating from friends/family, controlling finances)'), ('STALKING', 'Stalking or Persistent Unwanted Attention'), ('ONLINE_HARASSMENT', 'Online Harassment or Cyberbullying'), ('EMOTIONAL_MANIPULATION', 'Emotional Manipulation or Gaslighting'), ('FORCED_MARRIAGE', 'Forced Marriage or Honor-based Violence'), ('REPRODUCTIVE_COERCION', 'Reproductive Coercion (Forcing Pregnancy or Abortion)'), ('DENIAL_OF_EDUCATION', 'Denial of Education or Employment Opportunities')], max_length=50, null=True)),
                ('commonness_physical_violence', models.CharField(blank=True, choices=[('VERY_COMMON', 'Very Common'), ('SOMEWHAT_COMMON', 'Somewhat Common'), ('NOT_VERY_COMMON', 'Not Very Common'), ('NOT_AT_ALL_COMMON', 'Not At All Common'), ('UNSURE', 'Unsure')], max_length=20, null=True, verbose_name='In your opinion, how common is physical violence against women in your community?')),
                ('physical_violence_location', models.CharField(blank=True, choices=[('AT_HOME', 'At Home'), ('IN_PUBLIC_SPACES', 'In Public Spaces'), ('AT_WORK', 'At Work'), ('IN_EDUCATIONAL_INSTITUTIONS', 'In Educational Institutions')], max_length=30, null=True, verbose_name='Where do you think physical violence against women most commonly occurs?')),
                ('sexual_violence_prevalence', models.CharField(blank=True, choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('VERY_LOW', 'Very Low'), ('UNSURE', 'Unsure')], max_length=20, null=True, verbose_name='How would you rate the prevalence of sexual violence against women in your community?')),
                ('most_underreported_form', models.CharField(blank=True, choices=[('RAPE', 'Rape'), ('SEXUAL_ASSAULT', 'Sexual Assault'), ('UNWANTED_TOUCHING', 'Unwanted Touching or Groping'), ('FORCED_KISSING', 'Forced Kissing'), ('SHARING_IMAGES', 'Sharing Intimate Images Without Consent'), ('COERCION', 'Coercion Into Sexual Acts')], max_length=30, null=True, verbose_name='Which form of sexual violence do you think is most underreported?')),
                ('barrier_reporting', models.CharField(blank=True, choices=[('FEAR_RETALIATION', 'Fear of Retaliation'), ('SHAME_STIGMA', 'Shame or Stigma'), ('LACK_TRUST_AUTHORITIES', 'Lack of Trust in Authorities'), ('FEAR_NOT_BELIEVED', 'Fear of Not Being Believed'), ('LACK_AWARENESS', 'Lack of Awareness of Rights and Resources')], max_length=50, null=True, verbose_name='What is the biggest barrier to reporting sexual violence?')),
                ('emotional_abuse_recognition', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNSURE', 'Unsure')], max_length=10, null=True, verbose_name='Do you think emotional/psychological abuse is taken as seriously as physical violence?')),
                ('most_common_emotional_abuse', models.CharField(blank=True, choices=[('NAME_CALLING', 'Name-Calling or Insulting'), ('CONSTANT_CRITICISM', 'Constant Criticism'), ('HUMILIATION', 'Humiliation in Public or Private'), ('GASLIGHTING', 'Gaslighting'), ('THREATS', 'Threats'), ('ISOLATION', 'Isolation from Friends and Family')], max_length=30, null=True, verbose_name='Which form of emotional/psychological abuse do you think is most common?')),
                ('cyber_violence_prevalence', models.CharField(blank=True, choices=[('VERY_PREVALENT', 'Very Prevalent'), ('SOMEWHAT_PREVALENT', 'Somewhat Prevalent'), ('NOT_VERY_PREVALENT', 'Not Very Prevalent'), ('NOT_AT_ALL_PREVALENT', 'Not At All Prevalent'), ('UNSURE', 'Unsure')], max_length=20, null=True, verbose_name='How prevalent do you think cyber violence is against women?')),
                ('most_harmful_cyber_violence', models.CharField(blank=True, choices=[('online_harassment', 'Online Harassment or Bullying'), ('impersonation', 'Impersonation on Social Media'), ('revenge_porn', 'Revenge Porn'), ('doxxing', 'Doxxing')], max_length=50, null=True, verbose_name='Which form of cyber violence do you think is most harmful?')),
                ('response_to_violence', models.CharField(blank=True, choices=[('intervene_directly', 'Intervene Directly'), ('call_authorities', 'Call the Authorities'), ('offer_support', 'Offer Support to the Victim Afterwards'), ('nothing', 'Nothing, Out of Fear or Uncertainty')], max_length=50, null=True, verbose_name='If you witnessed violence against a woman, what would you most likely do?')),
                ('awareness_of_resources', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Are you aware of any local resources or organizations that support women experiencing violence?')),
            ],
        ),
    ]
