# Generated by Django 5.1.3 on 2025-03-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='familiarity_with_violence',
            field=models.CharField(blank=True, choices=[('VERY_FAMILIAR', 'Very familiar'), ('SOMEWHAT_FAMILIAR', 'Somewhat familiar'), ('NOT_VERY_FAMILIAR', 'Not very familiar'), ('NOT_AT_ALL_FAMILIAR', 'Not at all familiar')], max_length=50, null=True, verbose_name='Are you familiar with the term violence against women?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='forms_of_violence',
            field=models.CharField(blank=True, choices=[('PHYSICAL_ASSAULT', 'Physical assault (e.g., hitting, kicking, pushing)'), ('SEXUAL_ASSAULT', 'Sexual assault or rape'), ('VERBAL_ABUSE', 'Verbal abuse or name-calling'), ('CONTROLLING_BEHAVIOR', 'Controlling Behavior (e.g., isolating from friends/family, controlling finances)'), ('STALKING', 'Stalking or Persistent Unwanted Attention'), ('ONLINE_HARASSMENT', 'Online Harassment or Cyberbullying'), ('EMOTIONAL_MANIPULATION', 'Emotional Manipulation or Gaslighting'), ('FORCED_MARRIAGE', 'Forced Marriage or Honor-based Violence'), ('REPRODUCTIVE_COERCION', 'Reproductive Coercion (Forcing Pregnancy or Abortion)'), ('DENIAL_OF_EDUCATION', 'Denial of Education or Employment Opportunities')], max_length=50, null=True, verbose_name='Which of the following do you consider to be forms of violence against women?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='witnessed_violence',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=50, null=True, verbose_name='Have you ever witnessed or experienced any form of violence against women?'),
        ),
    ]
