# Generated by Django 5.1.3 on 2025-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_survey_familiarity_with_violence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Which of the following best describes your gender identity? Please select all that apply.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='state_union_territory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Union Territory : (Please specify)'),
        ),
    ]
