# Generated by Django 4.2.16 on 2024-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='gradient',
            field=models.CharField(blank=True, choices=[('primary', 'From Primary 400 to Primary 600'), ('secondary', 'From Secondary 400 to Secondary 600'), ('accent', 'From Accent 400 to Accent 600')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('FaSearch', 'Search Icon'), ('FaDesktop', 'Desktop Icon'), ('FaMobile', 'Mobile Icon'), ('FaDatabase', 'Database Icon'), ('FaCode', 'Code Icon'), ('FaChartLine', 'Chart Line Icon')], max_length=50, null=True),
        ),
    ]
