# Generated by Django 4.2.16 on 2024-11-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_project_key_features_project_results_and_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='results_and_impact',
        ),
        migrations.CreateModel(
            name='Keyfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Key_feature', to='Portfolio.project')),
            ],
        ),
    ]
