# Generated by Django 5.1.3 on 2024-11-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Benefit Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='careers/testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Career.department')),
            ],
            options={
                'ordering': ['-is_featured', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'state', 'city'],
                'unique_together': {('city', 'state', 'country')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20)),
                ('experience_years_min', models.PositiveIntegerField()),
                ('experience_years_max', models.PositiveIntegerField()),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_is_visible', models.BooleanField(default=True)),
                ('summary', models.TextField(help_text='A brief summary of the role')),
                ('description', models.TextField(help_text='Detailed job description')),
                ('responsibilities', models.TextField(help_text='Key responsibilities of the role')),
                ('requirements', models.TextField(help_text='Required qualifications and skills')),
                ('benefits', models.TextField(help_text='Job benefits and perks')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('filled', 'Position Filled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('applications_email', models.EmailField(help_text='Email where applications will be sent', max_length=254)),
                ('posting_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Career.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Career.joblocation')),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_jobs', to='Career.skill')),
                ('required_skills', models.ManyToManyField(related_name='required_jobs', to='Career.skill')),
            ],
            options={
                'ordering': ['-is_featured', '-posting_date'],
                'indexes': [models.Index(fields=['status', 'posting_date'], name='Career_jobp_status_82b074_idx'), models.Index(fields=['department', 'job_type'], name='Career_jobp_departm_7e4ddf_idx')],
            },
        ),
    ]
